//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Product
    {
        [Required(ErrorMessage ="商品番号は必須です")]
        [Range(1, 999,ErrorMessage = "商品番号は1から999のいずれかの値で入力してください")]
        public int 商品番号 { get; set; }
        [Required(ErrorMessage = "商品名は必須です")]
        public string 商品名 { get; set; }
        [Required(ErrorMessage = "価格は必須です")]
        [DisplayName("価格(円)")]
        public int 価格 { get; set; }
        public string 生産地 { get; set; }
    }
}
